config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :users, shallow: true do
    resources :favorites
  end

  namespace :admin do
    resources :gifs
    resources :categories
  end

  resources :categories, only: [:index, :show]
  resources :gifs, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category  < ApplicationRecord
  validates_presence_of :name
  has_many :gifs
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :gif
end

app/models/gif.rb
class Gif < ApplicationRecord
  validates_presence_of :image_path
  belongs_to :category
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  def self.category_select(category_name)
    category = Category.where(name: category_name).first
    something = Gif.where(category: category)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates_presence_of :password
  has_many :favorites, dependent: :destroy
  has_many :gifs, through: :favorites

  has_secure_password

  enum role: [:default, :admin]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  private

  def require_admin
    render file: '/public/404' unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to root_path
  end
end

app/controllers/admin/gifs_controller.rb
class Admin::GifsController < Admin::BaseController

  def new
    @gif = Gif.new
  end

  def create
    # @gif = Gif.create(gif_params)

    @category = Category.find_or_create_by(name: params[:category])
    api_instance = GiphyClient::DefaultApi.new

    api_key = ENV['giphy_api_key'] # String | Giphy API Key.

    opts = {
      tag: @category.name # String | Filters results by specified tag.
      # rating: "g", # String | Filters results by specified rating.
      # fmt: "json" # String | Used to indicate the expected response format. Default is Json.
    }

    result = api_instance.gifs_random_get(api_key, opts)

    @gif = @category.gifs.create(image_path: result.data.image_url)

    redirect_to gifs_path
  end

  def destroy
    gif = Gif.find(params[:id])
    gif.destroy
    redirect_to gifs_path
  end

  private

  def gif_params
    params.require(:gif).permit(:image_path)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :current_admin?

  def current_user
    @current_user = nil
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = Gif.find(params[:gif_id])
    user = User.find(params[:user_id])
    if user.gifs.include?(favorite)
      flash[:error] = 'Already in Favorites'
    else
      if favorite
        user.gifs << favorite
        flash[:success] = 'Added to Favorites!'
      else
        render :file => 'public/404'
      end
    end
    redirect_to gifs_path
  end

  def destroy
    favorite = Favorite.find(params[:id])
    favorite.destroy

    redirect_to user_path(current_user)
  end

  private

  def favorite_params
    params.permit(:user_id, :gif_id)
  end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController

  def index
    if params[:category]
      @gifs = Gif.category_select(params[:category])
      render 'gifs/categories'
    else
      @gifs = Gif.all
    end
  end

  def show
    @gif = Gif.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @favorites = Favorite.where(user_id: params[:id])
    @gifs = @favorites.map do |favorite|
      Gif.find_by(id: favorite.gif_id)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = 'Username already exists'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/gifs/new.html.erb
<h1>Create a Gif</h1>

 <%=form_tag admin_gifs_path do %>
  <%= label_tag :category %>
  <%= text_field_tag :category %>
  <%= submit_tag 'Generate Gif' %>
  <%end%>

app/views/gifs/categories.html.erb
<section class='all-gifs'>
  <% @gifs.each do |gif| %>
  <div class="gif-thumbnail">
    <div class='category-gif-thumbnail' id="gif<%=gif.id%>">
      <img class='gif' src="<%= gif.image_path %>" alt="<%=gif.id %>">
    </div>
  </div>
  <%end%>
</section>

app/views/gifs/index.html.erb
<h1 id='im-sleepy'>Gifs</h1>
<% if current_admin? %>
<%= link_to 'Add New Gif', new_admin_gif_path %>
<% end %>

<section class='all-gifs'>
  <% @gifs.each do |gif| %>
  <div class="gif-thumbnail">
    <div class='gif'id="gif-<%= gif.id%>">
      <%= link_to image_tag(gif.image_path, class: 'gif', alt: gif.id), gif_path(gif)%>
    </div>
    <div class='btn-container'>
      <% if current_admin? %>
      <%= link_to 'Delete', admin_gif_path(gif), method: 'delete' %>
      <%end%>
      <%if current_user != nil %>
      <div class="favorite">
        <%= form_tag user_favorites_path(current_user) do %>
        <%= hidden_field_tag :user_id, current_user.id %>
        <%= hidden_field_tag :gif_id, gif.id  %>
        <%= submit_tag "Add To Favorites" %>
        <%end%>
      </div>
      <%end%>
    </div>
  </div>
</div>
<%end%>
</section>

app/views/gifs/show.html.erb
<section class='show-gif'>
  <div id="gif-<%= @gif.id%>">
    <img class='gif-show' src='<%= @gif.image_path %>' alt='<%= @gif.id %>'>
  </div>
</section>

app/views/home/index.html.erb
<header id='index-header'>
  <h1>GifGenerator</h1>
  <h3>Where all your gif dreams come true!</h3>
  <div class="home-btns">
    <%= link_to 'All the Gifs', gifs_path, class: 'gif-index-home' %>
    <%= link_to 'Create Account', new_user_path, class: 'create-account' %>
  </div>
</header>



<div class="category-home">
  <h3 id='catys'>Categories</h3>
  <section class='categories'>
    <% @categories.each do |category| %>
    <div class='category-thumbnail' id="category-<%= category.id%>">
      <%=link_to category.name, "/gifs?category=#{category.name}", class: 'category-link' %>
      <div class="btn-container">
        <% if current_admin? %>
        <%=link_to 'Delete', admin_category_path(category), method: 'delete' %>
        <% end %>
      </div>
    </div>
    <%end%>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GifGenerator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  </head>

  <body>
    <nav>
      <%=link_to 'GifGenerator', root_path, class: 'big-nav' %>
      <%= link_to 'All Gifs', gifs_path, class: 'big-nav' %>

      <% if current_user != nil %>
        <%= link_to "#{current_user.username}", user_path(current_user), class: 'logger' %>
        <%= link_to 'Log out', logout_path, class: 'logger' %>
      <% else %>
        <%= link_to 'Log in', login_path, class: 'logger' %>
      <%end%>
    </nav>
    <div class="flash-message">
      <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="user-login">
  <main>
    <section class='login-new'>
      <%= form_for @user do |f| %>
      <div>
        <%= f.label :username  %>
        <%= f.text_field :username %>
      </div>
      <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <%= f.submit %>
      <%end%>
    </section>
  </main>
</div>

app/views/users/show.html.erb
<h1 class='kenny-logsout'>Welcome, <%= current_user.username %></h1>
<div class="user-logout">
  <%= link_to 'Log out', logout_path, class: 'kenny-logsout' %>
</div>

<section class='all-gifs'>
  <%@gifs.each do |gif| %>
  <div class="gif-thumbnail">
    <img class='gif' src="<%= gif.image_path%>" alt="picture">
    <div class="btn-container">
      <%= link_to 'Unfavorite', favorite_path(current_user.favorites.find_by(gif_id: gif.id)), class: 'unfavorite', method: 'delete' %>
    </div>
  </div>
  <%end%>
</section>